Update model_generator.rb to be compatible with Rails 5.2 (#107)
* Update model_generator.rb to be compatible with Rails 5.2 and newer

Why?
  When running "rails g noticed:model" under Rails 5.2, the error
  "NoMethodError: undefined method `configs_for' for #<Hash:...>"
  surfaces.  Rails 6.x and newer has this method, which works
  along with primary and replica database connections.  Rails 5.x
  does not support this behaviour.

How?
  Utilise ActiveRecord::Base#connection_config instead of refering
  to #configurations and from there using #configs_for.  Thankfully
  this is supported by older and newer versions of Rails.

* Fix small misspelling